### PR TITLE
Raise `ValueError` when parameter for GLM_single is misspelled

### PR DESCRIPTION
**Pull request by oliver-contier**
Just a minor suggestion after our discussion on potentially mixing up 'chunknum' and 'chunklen'. Any spelling mistakes would now stop the user before running `.fit()`.

Example
```
from glmsingle.glmsingle import GLM_single
gs = GLM_single(params=dict(
    chunknumber=1000,
))

```
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-8-74015f237f63> in <module>
      1 from glmsingle.glmsingle import GLM_single
----> 2 gs = GLM_single(params=dict(
      3     chunknumber=1000,
      4 ))

/LOCAL/ocontier/thingsmri/bids/code/external_libraries/GLMsingle/glmsingle/glmsingle.py in __init__(self, params)
    266                 Input parameter not recognized: '{key}'
    267                 Possible input parameters are:\n{list(default_params.keys())}
--> 268                 """)
    269 
    270         self.params = params

ValueError: 
                Input parameter not recognized: 'chunknumber'
                Possible input parameters are:
['numforhrf', 'hrfthresh', 'hrffitmask', 'R2thresh', 'hrfmodel', 'n_jobs', 'n_pcs', 'n_boots', 'extra_regressors', 'wantlibrary', 'wantglmdenoise', 'wantfracridge', 'chunklen', 'wantfileoutputs', 'wantmemoryoutputs', 'wantparametric', 'wantpercentbold', 'wantlss', 'brainthresh', 'brainR2', 'brainexclude', 'pcR2cutoff', 'pcR2cutoffmask', 'pcstop', 'fracs', 'wantautoscale', 'seed', 'suppressoutput', 'lambda']
```

### CODE REVIEW

**Review by iancharest — APPROVED** [review]
This looks good. ready to merge.

**Comment by kendrickkay** [comment]
I am happy to let you guys decide to merge in stuff for the Python world.  So @iancharest if it looks good, you can click the green button.

**Comment by kendrickkay** [comment]
Actualy, Ian tells me that the initiator of the pull request should Merge it.  So, @oliver-contier - go ahead!

**Comment by oliver-contier** [comment]
I don't think I can :/ Is it because I added another commit after @iancharest approved? If so, sorry for the hassle.
```
Only those with write access to this repository can merge pull requests.
```

**Comment by kendrickkay** [comment]
Oh I see.  Just now, I've added oliver to the contributors.  So now he has permission to write.

But for now, I went ahead and merged this pull request myself.

**Pull request merged**
